version: '3.1'
volumes:
  mysql-volume:
  ghost-volume:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - ggjam
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: blog-user
      MYSQL_PASSWORD: supersecret

  ghost:
    build: .
    hostname: ghost
    ports:
      - 2368:2368
    networks:
      - ggjam
    depends_on:
      - mysql
    restart: always
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: blog-user
      database__connection__password: supersecret
      database__connection__database: db
      storage__active: s3
      storage__s3__accessKeyId: ${GGJAM_S3_KEY}
      storage__s3__secretAccessKey: ${GGJAM_S3_SECRET}
      storage__s3__region: ${GGJAM_S3_REGION}
      storage__s3__bucket: ${GGJAM_S3_BUCKET}

networks:
  # The network created here needs to match the network in the gatsby frontend
  # or the frontend will not be able to talk to Ghost.
  ggjam:
